name: com.jc.livechat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6

  ## 启动图
  flutter_native_splash: ^2.3.5

  ## 屏幕适配
  flutter_screenutil: ^5.9.0

  ## 网络请求
  dio: ^5.3.3
  permission_handler: ^11.0.1

  ##
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  flutter_easyloading: ^3.0.5

  device_info_plus: ^9.1.0

  adaptive_action_sheet: ^2.0.1
  provider: ^6.0.1
  intl: any
  get_it: ^7.2.0
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.0.6
  image_picker: ^0.8.5+3
  file_picker: ^5.3.0
  tencent_super_tooltip: ^0.0.1
  video_player: ^2.7.0
  chewie_for_us: ^1.5.0
  flutter_slidable_for_tencent_im: ^1.4.0
  flutter_plugin_record_plus: ^0.0.16
  azlistview_all_platforms: ^2.1.2
  lpinyin: ^2.0.3
  transparent_image: ^2.0.0
  image_gallery_saver: ^2.0.1
  path_provider: ^2.0.8
  cached_network_image: ^3.3.0
#  shared_preferences: ^2.0.13
  scroll_to_index: ^2.1.1
  wechat_assets_picker: ^8.9.0-dev.1
  wechat_camera_picker: ^4.2.0-dev.2
  flutter_easyrefresh: ^2.2.1
  extended_image: ^8.2.0
  extended_text_field: ^13.0.0
  extended_text: ^12.0.0
  package_info_plus: ^4.0.1
  loading_animation_widget: ^1.1.0+3
#  permission_handler: ^10.2.0
  tuple: ^2.0.0
#  flutter_markdown: ^0.6.15
  url_launcher: ^6.1.4
  universal_html: ^2.2.2
  link_preview_generator_for_us: ^2.0.0
  http: ^1.0.0
  crypto: ^3.0.2
  collection: ^1.15.0
  flutter_image_compress: ^1.1.3
  uuid: ^3.0.6
  open_file: ^3.3.2
  tencent_keyboard_visibility: ^1.0.1
  tim_ui_kit_sticker_plugin: ^3.1.0
  tencent_im_base: ^3.1.0
  fc_native_video_thumbnail: any
  path: ^1.8.1
  tencent_cloud_uikit_core: ^1.2.1
  pasteboard: ^0.2.0
#  desktop_drop: ^0.4.4
#  device_info_plus: any
  cross_file: ^0.3.3+4
  csslib: 0.17.2
  diff_match_patch: ^0.4.1
  just_audio: ^0.9.34
  markdown: ^7.1.0
#  logger: ^2.0.1
  image_clipboard: ^1.0.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - images/login/
    - images/tim_kit/
    - images/tim_kit/svg/


