name: com.jc.livechat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6

  ## 启动图
  flutter_native_splash: ^2.3.5

  ## 屏幕适配
  flutter_screenutil: ^5.9.0

  ## 网络请求
  dio: ^5.3.3
  permission_handler: ^11.0.1

  ##
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  flutter_easyloading: ^3.0.5

  device_info_plus: ^9.1.0

  provider: ^6.0.1
  tencent_cloud_uikit_core: ^1.2.1
  tencent_keyboard_visibility: ^1.0.1
  tim_ui_kit_sticker_plugin: ^3.1.0
  tencent_im_base: ^3.1.0
  get_it: ^7.2.0
  package_info_plus: ^4.0.1
  loading_animation_widget: ^1.1.0+3
  extended_image: ^8.2.0
  extended_text_field: ^13.0.0
  extended_text: ^12.0.0
  intl: any
  flutter_slidable_for_tencent_im: ^1.4.0
  scroll_to_index: ^2.1.1
  video_player: ^2.7.0
  chewie_for_us: ^1.5.0
  flutter_plugin_record_plus: ^0.0.16
  flutter_easyrefresh: ^2.2.1
  wechat_assets_picker: ^8.9.0-dev.1
  wechat_camera_picker: ^4.2.0-dev.2
  image_picker: ^0.8.5+3
  file_picker: ^5.3.0
  just_audio: ^0.9.34


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - images/login/


